stages:
  - fetch
  - test

fetch-cypress:
  image: amazon/aws-cli:2.12.0
  stage: fetch
  only:
    - merge_requests
  script:
    - aws s3 cp s3://$AWS_BUCKET_NAME/cypress-latest.zip .
  variables:
    AWS_BUCKET_NAME: $AWS_BUCKET_NAME
  artifacts:
    paths:
      - cypress-latest.zip

test-frontend:
  image: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
  stage: test
  only:
    - merge_requests
  script:
    - mkdir cypress-e2e
    - unzip -P $CYPRESS_ZIP_PASSWORD cypress-latest.zip -d cypress-e2e
    - npm install
    - npm start &
    - cd cypress-e2e
    - npm install
    - npm run cypress
    - kill -9 $(ps aux | grep '/react-scripts/' | awk '{print $2}')
  artifacts:
    when: always
    paths:
      - cypress-e2e/cypress/reports
    expire_in: 1 day

